sonar.projectKey=wqza_url-link-extractor
sonar.organization=wqza
sonar.projectName=url-link-extractor
sonar.sources=url_link_extractor
sonar.tests=tests
sonar.language=python
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=tests/**
sonar.pullrequest.skip=true